services:
  - type: web
    name: hospital-bulk-processor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    autoDeploy: true
    plan: free
